### ISSUE TITLE
Module 'eos' has no attribute 'morphablemodel'

### ISSUE THREAD

**Issue by Jihosong** [patrikhuber/eos#177]
When I ran demo.py, I am getting this error. 
It worked when I used python 3.6, but after I downgraded to 3.5 to use dlib, I am getting this attribute error... It seems that the old issue was from typo 3440. But I made sure it's 3448. Any advice..? Thank you! 

`model = eos.morphablemodel.load_model('share/sfm_shape_3448.bin')
blendshapes = eos.morphablemodel.load_blendshapes('share/expression_blendshapes_3448.bin')
landmark_mapper = eos.core.LandmarkMapper('share/ibug_to_sfm.txt')
edge_topology = eos.morphablemodel.load_edge_topology('share/sfm_3448_edge_topology.json')
contour_landmarks = eos.fitting.ContourLandmarks.load('share/ibug_to_sfm.txt')
model_contour = eos.fitting.ModelContour.load('share/model_contours.json')`

**Comment by patrikhuber** [comment]
I think it should work with python-3.5 without a problem, I don't see a reason why it wouldn't. I think you've made an error locally somewhere. You posted quite a lot of lines, what happens if you only run one of them? What's the output of `help(eos)`?

**Comment by patrikhuber** [comment]
@Jihosong did you make any progress on this?

**Comment by ZhipengMei** [comment]
Hi @patrikhuber 
I am running into "module 'eos' has no attribute 'morphablemodel'" issue. 

Below is my error message:
```(py35) dhcp-39-9-219:python adrian$ python demo.py 
Traceback (most recent call last):
  File "demo.py", line 44, in <module>
    main()
  File "demo.py", line 11, in main
    model = eos.morphablemodel.load_model("../share/sfm_shape_3448.bin")
AttributeError: module 'eos' has no attribute 'morphablemodel'
```

I am running it in Anaconda python-3.5 environment:
```(py35) dhcp-39-9-219:python adrian$ python --version
Python 3.5.4 :: Anaconda, Inc.
```

I am not sure if I am following your guide in the readme file correctly. 
I tried to install eos-py with ```pip install eos-py```  but returns an error ```Failed building wheel for eos-py```

Any guidance would be greatly appreciated.

**Comment by patrikhuber** [comment]
Hi @ZhipengMei,

When you get above `AttributeError: module 'eos' has no attribute 'morphablemodel'`, you have not successfully installed `eos-py` yet, right? If it is not successfully installed, such an error would be expected.

So your problem is installing `eos-py`, and not above `AttributeError`, is that correct?

Can you maybe try `pip install eos-py -vvv`? I think this should give you more verbose output. And paste the compile output here?

**Comment by ZhipengMei** [comment]
@patrikhuber  

Thanks for the quick response. 
Yes, I have not successfully installed```eos-py```. I will spend more time on it later the today. I will update my progress here. 

Thanks for maintaining this project, bro.

**Comment by patrikhuber** [comment]
I'm closing this, the Python bindings are working for many people, so this must be an issue with not following installation instructions or something weird on the user's machine.
Feel free to re-open if you've followed my instructions and it seems like it indeed is an issue with eos. Thanks!

**Comment by mcbuehler** [comment]
The error `Module 'eos' has no attribute 'morphablemodel'` also occurs when you previously installed `pip install eos` (instead of `eos-py`). 

You can remove the other package and it should work:

 `pip uninstall eos`

**Comment by patrikhuber** [comment]
@mcbuehler Ah yes, good catch! Yes, unfortunately there was/is another module on PyPI called "eos". It's something completely unrelated and hasn't been updated in quite a while, so a clash where someone wants to use both in the same environment should not happen. You just need to know (from the readme) to install `eos-py`, if you want the package here :-).
